# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5585b1a84d9508ce0870a881c0a9fd8911b9926a13696d675370911d8e0c6b999d838de5ba3a5744151fd587acd90bdbd86d5d2cf475a45322f1ca41ade4e0df

test:
  secret_key_base: 2e0dd2de514a116be75504936f36f03843e81c446c6c27126ea8a7e29b9734463aba582b452f500c372c8fc4bb328b57b1accb48a889b556f91a54ba9f29436c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
